huhuran/views/machine.py
# coding: utf-8

from flask import (Blueprint, request, g, abort, jsonify,
                   render_template, url_for, redirect)
from eruhttp import EruException

from huhuran.ext import eru
from huhuran.config import PODNAME, DEPLOY_MODE
from huhuran.models import Machine, Image
from huhuran.utils import need_login, add_pubkey

bp = Blueprint('machine', __name__, url_prefix='/machine')


@bp.route('/')
@need_login
def index():
    machines = Machine.get_by_user(g.user)
    return render_template('index.html', machines=machines)


@bp.route('/<machine_id>/update', methods=['GET', 'POST'])
def callback(machine_id):
    machine = Machine.get(machine_id)
    if not machine:
        return 'not found'

    data = request.get_json()
    container_id = data['container_id']
    status = data.get('status')
    netaddr = data['networks'][0]['address']
    machine.set_alive(status == 'start')
    if not machine.container_id:
        machine.set_container_id(container_id)
        machine.set_netaddr(netaddr)
    return 'ok'


@bp.route('/create', methods=['GET', 'POST'])
@need_login
def create_machine():
    if request.method == 'GET':
        images = Image.list_all()
        return render_template('create_machine.html', images=images)

    name = request.form['name']
    image_name = request.form['image_name']
    if not (image_name and name):
        abort(400)

    image = Image.get_by_name(image_name)
    if not image:
        abort(400)

    machine = Machine.create(g.user, name)
    callback_url = url_for('machine.callback', machine_id=machine.id, _external=True)
    try:
        if DEPLOY_MODE == 'public':
            eru.deploy_public(PODNAME, image.appname, 1, image.version,
                              image.entrypoint, image.env, [image.network],
                              raw=True, image=image.addr,
                              callback_url=callback_url)
        elif DEPLOY_MODE == 'private':
            eru.deploy_private(PODNAME, image.appname, 1, 1, image.version,
                              image.entrypoint, image.env, [image.network],
                              raw=True, image=image.addr,
                              callback_url=callback_url)
    except EruException:
        pass
    return redirect(url_for('machine.index'))


@bp.route('/delete', methods=['POST'])
@need_login
def delete_machine():
    machine = Machine.get(request.form['machine_id'])
    if not machine:
        return jsonify(r=0)

    if machine.container_id:
        try:
            eru.remove_containers([machine.container_id])
        except EruException:
            pass

    machine.delete()
    return jsonify(r=0)


@bp.route('/alive', methods=['POST'])
@need_login
def is_alive():
    machine = Machine.get(request.form['machine_id'])
    if not machine:
        return jsonify(r=0)

    return jsonify(r=machine.is_alive)


@bp.route('/pubkey', methods=['POST'])
@need_login
def add_public_key():
    machine = Machine.get(request.form['machine_id'])
    if not (machine and machine.container_id):
        return jsonify(error=u'机器挂了')

    container = eru.get_container(machine.container_id)
    if not container['networks']:
        return jsonify(error=u'机器没有对外开放')

    netaddr = container['networks'][0]['address']
    if add_pubkey(g.user.pubkey, netaddr):
        return jsonify(error=u'添加成功')
    return jsonify(error=u'因为一些奇怪的原因添加失败')


@bp.route('/create_image', methods=['GET', 'POST'])
@need_login
def create_image():
    if request.method == 'GET':
        images = Image.list_all()
        return render_template('create_image.html', images=images)

    name = request.form['name']
    addr = request.form['addr']
    desc = request.form['desc']
    appname = request.form['appname']
    version = request.form['version']
    entrypoint = request.form['entrypoint']
    env = request.form['env']
    network = request.form['network']
    Image.create(name, addr, appname, version, entrypoint, env, network, desc)
    return redirect(url_for('machine.create_image'))


@bp.errorhandler(403)
@bp.errorhandler(404)
def error_handler(e):
    return render_template('%s.html' % e.code), e.code

huhuran/views/user.py
# coding: utf-8

from flask import Blueprint, request, session, redirect, url_for, abort

from huhuran.utils import need_login
from huhuran.oauth import sso

bp = Blueprint('user', __name__, url_prefix='/user')

@sso.tokengetter
def get_oauth_token():
    return session.get('sso')

@bp.route('/authorized')
def authorized():
    resp = sso.authorized_response()
    if resp is None:
        abort(400)
    session['sso'] = (resp['access_token'], '')
    return redirect(url_for('user.login'))

@bp.route('/login/')
def login():
    if 'sso' in session:
        return redirect(url_for('index.index'))
    return sso.authorize(
        callback=url_for('user.authorized', _external=True)
    )

@bp.route('/logout/')
@need_login
def logout():
    session.pop('sso')
    return redirect(url_for('index.index'))

huhuran/templates/admin.html
{% extends "/base.html" %}
{% import "/utils.html" as utils %}

{% block main %}
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td>Owner</td>
        <td>Status</td>
        <td>NetAddr</td>
        <td>Operation</td>
      </tr>
    </thead>
    <tbody>
      {% for machine in machines %}
        <tr>
          <td>{{machine.name}}</td>
          <td>{{machine.user_name}}</td>
          <td>{{'运行' if machine.is_alive else '挂了'}}</td>
          <td>{{machine.netaddr}}</td>
          <td>
            <a data-machine-id="{{machine.id}}" class="btn btn-xs btn-warning btn-remove" href="#">不要了</a>
            <a data-machine-id="{{machine.id}}" class="btn btn-xs btn-warning btn-pubkey" href="#">加我的公钥</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {{utils.paginator(g.start, total, g.limit, endpoint)}}
{% endblock %}

{% block bottom_script %}
<script>
  $('a.btn-remove').click(function (){
    if (!confirm('确认不要了, 没提交的都没了哈')) {
      return;
    }
    var self = $(this);
    $.post('/machine/delete', {machine_id: self.data('machine-id')}, function(){
      self.parent().parent().remove();
    });
  });

  $('a.btn-pubkey').click(function (){
    var self = $(this);
    $.post('/machine/pubkey', {machine_id: self.data('machine-id')}, function(r){
      alert(r.error);
    });
  });
</script>
{% endblock %}

huhuran/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} · Huhuran Princess</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <link href="/huhuran/static/css/vendor/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/huhuran/static/css/flat-ui.min.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <script src="/huhuran/static/js/vendor/jquery.min.js"></script>
    <script src="/huhuran/static/js/flat-ui.min.js"></script>
    <script src="/huhuran/static/js/application.js"></script>
    {% block more_header %}{% endblock %}
    <style>
      {% block more_css %}{% endblock more_css %}
      nav.navbar {border-radius: 0!important;}
    </style>
    <!-- COLLECTED CSS -->
  </head>

  <body>
    <!-- Docs master nav -->
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <a href="{{url_for('index.index')}}" class="navbar-brand">Huhuran</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="{{'active' if request.path == url_for('machine.index') else ''}}">
            <a href="{{url_for('machine.index')}}"><span class="fui-list-bulleted"></span> 我的机器</a>
          </li>
          <li class="{{'active' if request.path == url_for('machine.create_machine') else ''}}">
            <a href="{{url_for('machine.create_machine')}}"><span class="fui-plus"></span> 开个新的</a>
          </li>
          {% if g.user and g.user.admin %}
            <li class="{{'active' if request.path == url_for('machine.create_image') else ''}}">
              <a href="{{url_for('machine.create_image')}}"><span class="fui-gear"></span> 管理镜像</a>
            </li>
            <li class="{{'active' if request.path == url_for('admin.index') else ''}}">
              <a href="{{url_for('admin.index')}}"><span class="fui-list-large-thumbnails"></span> 管理Cell </a>
            </li>
          {% endif %}

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{g.user.name or '未登录'}} <b class="caret"></b></a>
            <ul class="dropdown-menu">
              {% if g.user %}
              <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
              {% else %}
              <li><a href="{{ url_for('user.login') }}">Login</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      <div>
    </nav>

    <!-- Docs page layout -->
    <div class="bs-header" id="content">
      <div class="container">
        {% block more_content_header %}{% endblock %}
      </div>
    </div>

    <div class="container bs-docs-container">
      <div class="row">
      {% block main %}
        <div class="col-md-3">
          {% block main_left %}
          {% endblock %}
        </div>
        <div class="col-md-9">
          {% block main_right%}
          {% endblock %}
        </div>
      {% endblock %}
      {% block sidebar %}{% endblock %}
      </div>
    </div>

    <!-- Footer ================================================== -->
    <footer class="footer container">
        {% block footer %}{% endblock %}
    </footer>

    <!-- Le javascript ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block bottom_script %}{% endblock %}
    <!-- COLLECTED JS -->
  </body>
</html>

huhuran/templates/create_image.html
{% extends "/base.html" %}

{% block main %}
<table class="table table-stripped">
  <thead>
    <tr>
      <td>Name</td>
      <td>Addr</td>
      <td>Appname</td>
      <td>Version</td>
      <td>Entrypoint</td>
      <td>Env</td>
      <td>Network</td>
      <td>Description</td>
    </tr>
  </thead>
  <tbody>
    {% for i in images %}
    <tr>
      <td>{{i.name}}</td>
      <td>{{i.addr}}</td>
      <td>{{i.appname}}</td>
      <td>{{i.version}}</td>
      <td>{{i.entrypoint}}</td>
      <td>{{i.env}}</td>
      <td>{{i.network}}</td>
      <td>{{i.desc}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<form class="form-horizontal" method="post" action="{{url_for('machine.create_image')}}">
  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-offset-2">
      <input name="name" type="text" class="form-control" placeholder="Name, only letters">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Addr</label>
    <div class="col-sm-offset-2">
      <input name="addr" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Appname</label>
    <div class="col-sm-offset-2">
      <input name="appname" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Version</label>
    <div class="col-sm-offset-2">
      <input name="version" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Entrypoint</label>
    <div class="col-sm-offset-2">
      <input name="entrypoint" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Env</label>
    <div class="col-sm-offset-2">
      <input name="env" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Network</label>
    <div class="col-sm-offset-2">
      <input name="network" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-offset-2">
      <input name="desc" type="text" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <button type="submit" class="btn btn-primary">就决定是你了!</button>
    </div>
  </div>
</form>
{% endblock %}

huhuran/templates/create_machine.html
{% extends "/base.html" %}

{% block main %}
<form class="form-horizontal" method="post" action="{{url_for('machine.create_machine')}}">
  <div class="form-group">
    <label class="col-sm-2 control-label" for="">Image Name</label>
    <div class="col-sm-offset-2">
      <select name="image_name" class="form-control">
        {% for image in images %}
        <option value="{{image.name}}">{{image.name}} - {{image.desc}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-offset-2">
      <input name="name" type="text" class="form-control" placeholder="Name, only letters">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <button type="submit" class="btn btn-primary">就决定是你了!</button>
    </div>
  </div>
</form>
{% endblock %}

huhuran/templates/index.html
{% extends "/base.html" %}

{% block main %}
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td>Status</td>
        <td>NetAddr</td>
        <td>Operation</td>
      </tr>
    </thead>
    <tbody>
      {% for machine in machines %}
        <tr>
          <td>{{machine.name}}</td>
          <td class="td-ready" data-machine-id="{{machine.id}}">{{'运行' if machine.is_alive else '挂了'}}</td>
          <td>{{machine.netaddr}}</td>
          <td>
            <a data-machine-id="{{machine.id}}" class="btn btn-xs btn-warning btn-remove" href="#">不要了</a>
            <a data-machine-id="{{machine.id}}" class="btn btn-xs btn-warning btn-pubkey" href="#">加我的公钥</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block bottom_script %}
<script>
  $('a.btn-remove').click(function (){
    if (!confirm('确认不要了, 没提交的都没了哈')) {
      return;
    }
    var self = $(this);
    $.post('/machine/delete', {machine_id: self.data('machine-id')}, function(){
      self.parent().parent().remove();
    });
  });

  $('a.btn-pubkey').click(function (){
    var self = $(this);
    $.post('/machine/pubkey', {machine_id: self.data('machine-id')}, function(r){
      alert(r.error);
    });
  });
</script>
{% endblock %}

huhuran/templates/init.html
{% extends "/base.html" %}
{% block main %}
<h3>登陆去吧你</h3>
{% endblock %}

huhuran/templates/utils.html
{% macro paginator(start, total, perpage, endpoint) %}

  {% set cur_page = start // perpage + 1 %}
  {% if total % perpage == 0 %}
  {% set total_page = total // perpage %}
  {% else %}
  {% set total_page = total // perpage + 1 %}
  {% endif %}
  {% set begin = max(cur_page-3, 1) %}
  {% set end = min(cur_page+3, total_page) %}
  {% set prev = 'disabled' if cur_page <=1 else '' %}
  {% set next = 'disabled' if cur_page >= total_page else '' %}
  {% set prev_num = max((cur_page-2)*perpage, 0) %}
  {% set kw = paginator_kwargs(kwargs) %}

  {% if total > 0 %}
    <ul class="pagination-plain">
      {% if cur_page != 1 %}
      <li class="previous {{prev}}">
        <a href="{{url_for(endpoint, start=prev_num, limit=perpage, **kw)}}">
          <span class="fui-triangle-left-large"></span> 上一页
        </a>
      </li>
      {% endif %}
      {% for i in range(begin, end+1) %}
        <li class="{{'active' if cur_page == i else ''}}">
          <a href="{{url_for(endpoint, start=(i-1)*perpage, limit=perpage, **kw)}}">{{i}}</a>
        </li>
      {% endfor %}
      <li class="next {{next}}">
        {% if cur_page != total_page %}
        <a href="{{url_for(endpoint, start=cur_page*perpage, limit=perpage, **kw)}}">
          下一页 <span class="fui-triangle-right-large"></span>
        </a>
        {% endif %}
      </li>
    </ul>
  {% endif %}

{% endmacro %}

{# vim:set ft=jinja: #}